### ISSUE TITLE
Signs sometimes overlap weirdly

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#132]
![grafik](https://user-images.githubusercontent.com/49159623/83952223-9d109a00-a837-11ea-9364-3c730e60a986.png)
I do not really know how this can be resolved. Do you have an idea, @holke ?

**Comment by holke** [comment]
Looks to me like a layer problem.
If two objects are in the same render layer, they can get mixed up, because the order in which they are added to the screen is arbitrary.
This order can even change from frame to frame and thus result in flickering (i did not see this with the signs, just saying it can happen).
I guess the only way to avoid it is to assign different signs to different render layers.

**Comment by maccxs** [comment]
Thank you that was a good idea. I now adapted the picture of the hand so it can have the same layer as the npc and the sign. They are now not in different layers, but all NPCs with a sing live in the same layer but get assigend a different sorting order in the layer.
