### ISSUE TITLE
White border around menu

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#36]
There seems to be a white boarder around the menus, which is also different in size on different systems.
Here is a screenshot from @maccxs 

![grafik](https://user-images.githubusercontent.com/7125317/78646332-2e57a480-78b9-11ea-9f4a-8b3a930df003.png)

And here a screenshot from me:

![WhiteBoundary](https://user-images.githubusercontent.com/7125317/78646565-855d7980-78b9-11ea-8329-97ef7bf8ae72.PNG)

**Comment by maccxs** [comment]
@holke @FredyHennig My game suddenly looks like this 
![grafik](https://user-images.githubusercontent.com/49159623/78779438-4274d200-799d-11ea-8623-1ba03ba76eb1.png)
Even after removing everything and getting the new master. HAve any ideas?

**Comment by ghost** [comment]
Did you resize your viewport window?

**Comment by holke** [comment]
After build and run or inside unity?`
I cannot replicate this.

**Comment by ghost** [comment]
Ah, I see what's wrong. For some reason, your camera viewport has become larger than the map background.
I reproduced it by setting the viewport aspect ratio to "Free Aspect" and resizing the window. Fixing the aspect ratio to e.g. 16:9 solves the problem. 

In fact, that is also the reason for the white border! It also appears at certain aspect ratios. The white border comes from the *Image* object. 

But for robustly solving the problem, I guess we should extend the MapLimits script to resize the background so that it covers the entire map....

I'm experimenting with the UI objects to remove the white border.

**Comment by maccxs** [comment]
Thanks, that would be great!

**Comment by maccxs** [comment]
At least for the website, we have to make sure that the borders are ok.

**Comment by maccxs** [comment]
And I don't really know how to do it ...

**Comment by ghost** [comment]
@maccxs I think I can solve it, but it would involve tearing and stretching the background image to viewport size. I don't want to deform the virus images, so I'd fill the screen with a monochromatic background, and put the virus images above that as an overlay. Could you give me the original virus images on a transparent background for that?

Supplement: I've cut them out myself, but the borders aren't perfect. I guess it would look better with the original pictures.
