### ISSUE TITLE
Implement Level 3

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#80]
Collect face masks for the local hospital.

**Comment by holke** [comment]
Requires #86

**Comment by holke** [comment]
While working on this I want to ask for your opinion:

Which way is better:

1. there is one mask on the map and when the player collects it a new one appears. Like snake.
2. all n masks are on the map at the same Time.

**Comment by maccxs** [comment]
I like both :-)

**Comment by holke** [comment]
A first version is online.
Still rudimentary and does not abort if the player gets infected.
But you can check it out for a first look.

**Comment by maccxs** [comment]
Sorry, that things got lost. yesterday. Saw the commit message. I like the mask counter and the rotation of the masks. Really nice :-)  I like it :-) Is it intended that there are so many NPCs? Can't be, because it's impossible not to get infected.  Also, unfortunately, unity crashed while playing the level. Second time I could play to the end, so maybe not a bug after all.
What do you think about taking the Canvas that I introduced in levelgethome for all levels? So not different endscreens when the player fails but the Canvas appears in the game? Then I would do this for the levelsupermarket and the party level as well. You could simply copy the game objects and the button controller from levelgethome. Then the end game controller sets the canvas as active when the game is lost or finally won. Next scene then would be the intro to party level.

**Comment by holke** [comment]
Thanks for your feedback :)
Of unity crashes again please let me know!

This is still wip, things that will change:
- tweak npc number
- change number of masks needed (maybe 10?)
- proper intro text 
- use new levelgethome features
    - transparent Ui win/lost as you say
    - smiles don’t change color
