### ISSUE TITLE
General script for all levels so that game ends early when player is infected

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#95]

**Comment by maccxs** [comment]
My idea is that the game pauses when the player is infected. Then a text appears which tells the user to continue with 'c' or retry with 'r'. This should be kept general so that it can be applied without further ado to all levels where we need it.

**Comment by holke** [comment]
The end condition can easily be implemented in EndLevelControllerBase, each EndLevelCotroller that inherits can the decide whether or not to apply it.

With 'continue' do you mean: Continue this level as an infected human and see what happens, or continue to the next level?

**Comment by maccxs** [comment]
Continue this level as infected human.

Am Mo., 4. Mai 2020 um 10:56 Uhr schrieb holke <notifications@github.com>:

**Comment by holke** [comment]
Yes, thats the better option. 
This fits into my plans for #87 and could be developed in conjunction with it.
A GameManager that knows the order of levels/scenes and in which scene we are currently in.
So that the levels do not have to care about what level comes next.
This game manager can then also call your new menu and give control back to the level or restart it.

**Comment by maccxs** [comment]
That sounds like a plan.
